# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Services"
  url = "#services"
  weight = 20

[[main]]
  name = "Data Ecosystems"
  url = "#observatories"
  weight = 25

[[main]]
  name = "Team"
  url = "#team"
  weight = 30

[[main]]
  name = "News"
  url = "#posts"
  weight = 15


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Software"
  url = "/software/"
  weight = 50


[[main]]
  name = "Publications"
  url = "#featured"
  weight = 70


[[main]]
  name = "Talks"
  url = "#talks"
  weight = 85

[[main]]
  name = "Data&Lyrics Blog"
  url = "https://dataandlyrics.com/"
  weight = 95

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
