main:
  - name: Home
    url: ''
    weight: 10
    identifier: Home
  - name: About
    url: '#about'
    weight: 10
    parent: Home
  - name: Achievements
    url: '#achievements'
    weight: 12
    parent: Home
  - name: Services
    url: '#services'
    weight: 14
    parent: Home
  - name: Blog
    url: '#posts'
    weight: 20
  - name: Data Ecosystems
    url: ""
    weight: 30
    identifier: Data
  - name: Overview
    url: '#observatories'
    weight: 30
    parent: Data
  - name: Digital Music Observatory &#128279;
    url: 'https://music.dataobservatory.eu'
    weight: 31
    parent: Data
  - name: CCSI Data Observatory &#128279;
    url: 'https://ccsi.dataobservatory.eu'
    weight: 32
    parent: Data
  - name: Green Deal Data Observatory &#128279;
    url: 'https://greendeal.dataobservatory.eu'
    weight: 33
    parent: Data
  - name: Competition Data Observatory &#128279;
    url: 'https://competition.dataobservatory.eu'
    weight: 34
    parent: Data
  - name: Team
    url: '#team'
    weight: 40
  - name: Software
    url: '#software'
    weight: 50
    identifier: software
  - name: Projects
    url: "#projects"
    weight: 60
  - name: Publications
    url: '#featured'
    weight: 70
    identifier: Publications
  - name: Featured
    url: '#featured'
    weight: 70
    parent: Publications
  - name: All Publications
    url: '#publications'
    weight: 72
    parent: Publications
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 90
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
